### ISSUE TITLE
Basic tool guide

### ISSUE THREAD

**Issue by Seanny123** [nengo/design#3]
I was hoping to modify the Nengo DL logo to make one for Nengo SPA. I know the original logo was made using Inkscape, but I'm having trouble using this tool to modify the text of the logo. How do I set the font tool appropriately? I know the font is Sanchez, but there appears to be some other stuff going on. Could this be documented somewhere?

**Comment by tbekolay** [comment]
Hm... I'm not sure it makes sense to add Inkscape instructions to this repo, best to leave Inkscape tutorials to Inkscape people. Also, it's fine if someone wants to do their designs in Adobe Illustrator as long as they export to a plain SVG.

The only think that I think is happening in our Inkscape stuff other than using the text tool is to convert the text to a path (Path > Object to Path). For the N, that's how I made the manual adjustments (e.g., removing the middle stroke). For the other letters, maybe there were some manual kerning adjustments, but you have to be careful with kerning or it'll look super weird.

Also note that the font for the project-specific logos doesn't have to match the font of the Nengo part. Having a different font for that part could help distinguish projects so that the logo doesn't look like it was automatically created.

**Comment by jgosmann** [comment]
> but you have to be careful with kerning or it'll look super weird

Obligatory kerning XKCD: 😀 

![kerning](https://imgs.xkcd.com/comics/kerning.png)

> Also note that the font for the project-specific logos doesn't have to match the font of the Nengo part.

But also keep in mind that matching fonts is also not always easy.

**Comment by tbekolay** [comment]
> But also keep in mind that matching fonts is also not always easy.

That's what makes it fun!

**Comment by Seanny123** [comment]
> Also note that the font for the project-specific logos doesn't have to match the font of the Nengo part. Having a different font for that part could help distinguish projects so that the logo doesn't look like it was automatically created.

Ah, I thought I had to match the font, which I why I was asking this whole question in the first place. Given that this is not necessary, I'll close this issue or should this be written down somewhere in the design doc? I keep asking these questions, because I'm *super* unfamiliar with design and the documentation of it.

**Comment by tbekolay** [comment]
I tried to document that here: https://www.nengo.ai/design/guidelines.html#project-branding

Specifically,

>Aside from incorporating the general Nengo logo and coloring the tuning curves as described above, the project is free to add their own touches in terms of how they add the rest of the project name to the logo.

I was meaning to leave that description vague so that enterprising designers could add extra touches if they wanted, but if it's too vague feel free to suggest changes to that paragraph.

**Comment by Seanny123** [comment]
Nah, that paragraph is fine. I just failed at to RTM properly.
